version: '3.4'
services:

########################
# sneaky_c2

  preflight:
    container_name: sneaky_c2
    build:
      context: ./
      dockerfile: Dockerfile
      network: host
      args:
        -  'REDIRECT_URL=${REDIRECT_URL}'
        -  'PROXY_DOMAIN=${PROXY_DOMAIN}'
        -  'HIDDEN_HOST=${HIDDEN_HOST}'
    ports:
      - 443:443
      - 80:80
    image: sneaky_c2
